ENH: Move deleted functions to public
The compiler will produce a more specific error message, when a public
deleted function is called, rather than when a private deleted function
is called.

VS2015 produces the following error on an attempt to call a public deleted function:
  error C2280: 'A &A::operator =(const A &)': attempting to reference a deleted function

While it produces the following error on an attempt to call a private deleted function:
  error C2248: 'A::operator =': cannot access private member declared in class 'A'