Fix bug 427
Depending on the user installation, the compiled library will have missing symbols. e.g. Manjaro/Linux, VTK-7.1:

ImportError: /home/user/gdcm-2.6.8/build/bin/libvtkgdcm.so.2.6: undefined symbol: _Z40vtkFiltersParallelDIY2_AutoInit_Destructv

It can even crash when trying to execute from libvtkgdcmPython import *