Revert "COMP: Add explicit assignment operators for Item"
This reverts commit 61ef40c92d5052e755cee53d1d4d0b01ad053a5b.

gdcmItem.h(97): error C2610: 'gdcm::Item &gdcm::Item::operator =(gdcm::Item &&)' : is not a special member function which can be defaulted