COMP: API changes for charls
Build error related API update of charls.

gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:100:9: error: no matching function for call to 'JpegLsReadHeader'
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:100:58: error: use of undeclared identifier 'OK'
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:108:27: error: no member named 'bitspersample' in 'JlsParameters'; did you mean 'bitsPerSample'?
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:155:22: error: no member named 'bitspersample' in 'JlsParameters'; did you mean 'bitsPerSample'?
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:172:48: error: no member named 'bitspersample' in 'JlsParameters'; did you mean 'bitsPerSample'?
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:189:5: error: no matching function for call to 'JpegLsReadHeader'
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:193:61: error: no member named 'bitspersample' in 'JlsParameters'; did you mean 'bitsPerSample'?
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:196:5: error: unknown type name 'JLS_ERROR'
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:197:7: error: no matching function for call to 'JpegLsDecode'
gdcm/Examples/Cxx/FixJAIBugJPEGLS.cxx:198:19: error: use of undeclared identifier 'OK'