Remove OSX + Java for now
SWIG 4.0 is giving some weird compilation error which will needs to be adressed at some point:

gdcm/MappingType.java:85: error: incompatible types: Iterator cannot be converted to SWIGTYPE_p_std__mapT_char_const_p_std__mapT_gdcm__Tag_char_const_p_std__lessT_gdcm__Tag_t_t_std__lessT_char_const_p_t_t__iterator