Issue: gdcm 2.8.1 with Python
Revert "Problem extracting pixel data from Python 3"

This reverts commit 7a1ffcb71bd995896a91b8dcceb7ad2a299d7379.

Full message:

Hello,

Have tried to upgrade from gdcm 2.6.8 to gdcm 2.8.1.
OS: Windows 10 x64.
Built from source using MS VS2015. Release version. Successful.

Try to run gdcm 2.8.1 in the same version Python 3.6.1 as before
but received the following new error message during gdcm import.
_____

in <module> import gdcm

  File "E:\Program Files\gdcm\bin\Release\gdcm.py", line 74, in <module>
    Global.GetInstance().Prepend( os.path.dirname(__file__) + "/../../../"  + GDCM_INSTALL_DATA_DIR + "/XML/" )

TypeError: must be str, not bytes
_____

IDE: Spyder 3.1.4 with PythonPath to gdcm E:\Program Files\gdcm\bin\Release

CMake 3.8.2 gave the following warning:

CMake Deprecation Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/UseSWIG.cmake:226 (message):
SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
Wrapping/Python/CMakeLists.txt:93 (SWIG_ADD_MODULE)

SWIG: 3.0.12

Any insight would be appreciated.

Thank you.