Revert "Fixed several clang -Wdeprecated-dynamic-exception-spec warnings"
This reverts commit 6da731836814b137da1a04953449388b2fff2ce1.

---

Fix

c:\projects\gdcm\utilities\socketxx\socket++\sockstream.h(93): error C3646: 'noexcept' : unknown override specifier [C:\projects\gdcm\Utilities\socketxx\socket++\socketxx.vcxproj]