Revert "Add support for MappingType"
This reverts commit 6f027472d0d3d256395ce18229c81410c5bde1fd.

This was causing compilation error on MacOSX:

gdcm/MappingType.java:85: error: incompatible types: Iterator cannot be converted to SWIGTYPE_p_std__mapT_char_const_p_std__mapT_gdcm__Tag_char_const_p_std__lessT_gdcm__Tag_t_t_std__lessT_char_const_p_t_t__iterator