REvert: our changes to CreateWhat look fine to me, but __FUNCTION__ cannot be used as default argument.  It says:  error C2457: '__FUNCTION__': predefined macro cannot appear outside of a function body So instead, __FUNCTION__ should be specified as argument at the location where the gdcm::Exception object is actually constructed. comments from Niels